markdown: kramdown

title: Alexey needs a web presence
author: Alexey Komissarouk
domain: http://alexeymk.com

tag_title_prefix: ! "Posts on \""

plugins: [jekyll-paginate]
paginate: 5
paginate_path: ":num"

timezone: America/Los_Angeles

exclude: ["TODO", "README.md", "*.py", "*.rb", "*.sh", "Gemfile*", "__*"]
