markdown: kramdown

title: "Alexey needs a web presence"
description: "Alexey Komissarouk's blog on growth engineering, startups, and technology."
url: "https://alexeymk.com"
domain: https://alexeymk.com
author:
  name: Alexey Komissarouk
  email: alexey@alexeymk.com
  twitter: alexeymk

tag_title_prefix: ! "Posts on \""

plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 5
paginate_path: ":num"

timezone: America/Los_Angeles

exclude: ["TODO", "README.md", "*.py", "*.rb", "*.sh", "Gemfile*", "__*"]
