title: Alexey needs a web presence
description: Alexey needs a web presence
url: 'https://alexeymk.com'
#baseurl: 'https://alexeymk.com'
google:
 siteverification:
 analystic: UA-177075467-9
 tagmanager: GTM-T3ZC4Q3W
lang: en
locale: en_US
timezone: 'America/Los_Angeles'
media:
 favicon: /assets/img/alexey.webp
 cover: /assets/img/alexey.webp

# this is specifically the ID of the form embed
beehiiv_id: e6e4a431-4ee3-491e-ad72-a3b738eaa350

author:
 name: Alexey MK
 image: /assets/img/alexey.webp
 about: About Alexey MK - Starting, scaling, and optimizing a Software Engineering Organization focused on Growth
 text: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
 email: alexey@alexeymk.com

popularposttitle: Featured Essays
popularpost:
 - title: Stat Sig on a Shoestring Budget
   link: /2023/09/11/statistical-significance-on-a-shoestring-budget.html
   description: Techniques for running A/B tests with limited traffic
 - title: Build a Growth Engineering Team That Wins
   link: /2023/09/27/how-to-build-a-growth-engineering-team-that-wins.html
   description: Starting, hiring, training, and setting culture for your Growth Engineering team. Co-authored with Elena Verna
 - title: Lies, Damned Lies, and Front-end Tracking
   link: /2020/07/14/lies-damn-list-and-front-end-tracking.html
   description: Front-end analytics can be deceptive. Here's what you should do instead.
 - title: Product Engineers Can't Hack it on Growth
   link: /2023/03/03/why-core-product-engineers-cant-hack-growth.html
   description: "Why so many growth engineers coming from product don't seem to enjoy their job"

postlist:
 title: Latest Articles
 button: Explore all post
 limit: 8

paginationpage:
 next: _
 previous: More

footernavtitle: Menu
footernav1:
 nav: Home
 link: /
footernav2:
 nav: About
 link: /about
footernav3:
 nav: Growth
 link: /growth-eng
footernav4:
 nav: Contact
 link: mailto:alexey+contact-on-website@alexeymk.com

sharemodal:
 button: Share article
 title: Share this article
 description: In you liked this article share it with your friends. They will thank you later.
 email: email
 twitter: tweet
 facebook: facebook

social: #max 5 social
 facebook:
 twitter: https://twitter.com/alexeymk
 twitter_username: alexeymk
 rss: /feed.xml
 linked:
 youtube:
# instagram:


paginate: 6
paginate_path: '/:num/'

collections:
  services:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      permalink: /:year/:month/:title:output_ext.html
      permalink:
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
