title: Alexey needs a web presence
description: Alexey needs a web presence
url: 'https://alexeymk.com'
#baseurl: 'https://alexeymk.com'
google:
 siteverification:
 analystic: G-82F5K9G4DY
 tagmanager: GTM-T3ZC4Q3W
lang: en
locale: en_US
timezone: 'America/Los_Angeles'
media:
 favicon: /images/alexey.webp
 cover: /images/alexey.webp

# this is specifically the ID of the form embed
beehiiv_id: e6e4a431-4ee3-491e-ad72-a3b738eaa350

author:
 name: Alexey MK
 image: /images/alexey.webp
 email: alexey@alexeymk.com

popularposttitle: Growth Engineering Guides
popularpost:
 - title: "How to Prioritize (using RICE and DRICE)"
   link: https://www.lennysnewsletter.com/p/introducing-drice-a-modern-prioritization
   coauthor: "Written with Darius Contractor. Published on Lenny's Newsletter"
   description: "Prioritization, done right, is one of the highest-leverage ways a PM can help their team"
 - title: Hiring, Training, and Culture for Growth Eng
   link: /2023/09/27/how-to-build-a-growth-engineering-team-that-wins.html
   coauthor: "Co-authored with Elena Verna"
   description: Building a Growth Engineering Organization requires a different skillset.
 - title: Lifecycle Marketing Tech Stack
   link: https://playbooks.hypergrowthpartners.com/p/picking-your-lifecycle-marketing
   coauthor: Written with Tatteo Tittarelli. Published with HyperGrowth Partners.
   description: How to select, implement and scale marketing communication tooling, from 0 to IPO.
 - title: DNA of a Great Growth Engineer
   link: https://www.youtube.com/watch?v=fFZBZJrnUIg
   coauthor: Talk given at Reforge
   description: Great Growth Engineers have a particlar set of skills. Skills they have acquired as quickly as possible.
 - title: Statistical Significance on a Budget
   link: /2023/09/11/statistical-significance-on-a-shoestring-budget.html
   description: No traffic, no problem! Updating your setup so you can keep experimenting.
 - title: Front-end Analytics Gotchas
   link: /2020/07/14/lies-damn-list-and-front-end-tracking.html
   description: "\"The slower your website, the better it converts\" and other lies your front-end analytics will tell you."

postlist:
 title: Latest Articles
 button: Explore all post
 limit: 8

paginationpage:
 next: _
 previous: More

footernavtitle: Menu
footernav1:
 nav: Home
 link: /
footernav2:
 nav: About
 link: /about
footernav3:
 nav: Growth
 link: /growth-eng
footernav4:
 nav: Contact
 link: mailto:alexey+contact-on-website@alexeymk.com

sharemodal:
 button: Share article
 title: Share this article
 description: If you liked this article share it with your friends. They will thank you later.
 email: email
 twitter: tweet
 facebook: facebook

social: #max 5 social
 facebook:
 twitter: https://twitter.com/alexeymk
 twitter_username: alexeymk
 rss: /feed.xml
 linked:
 youtube:
# instagram:


paginate: 10
paginate_path: '/:num/'

collections:
  services:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      permalink: /:year/:month/:title:output_ext.html
      permalink:
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
