title: Alexey needs a web presence
description: Alexey needs a web presence
url: 'https://alexeymk.com'
#baseurl: 'https://alexeymk.com'
google:
 siteverification:
 analystic: UA-177075467-9
 tagmanager: GTM-T3ZC4Q3W
lang: en
locale: en_US
timezone: 'America/Los_Angeles'
media:
 favicon: /assets/img/alexey.webp
 cover: /assets/img/alexey.webp

# this is specifically the ID of the form embed
beehiiv_id: e6e4a431-4ee3-491e-ad72-a3b738eaa350

author:
 name: Alexey MK
 image: /assets/img/alexey.webp
 email: alexey@alexeymk.com

popularposttitle: Growth Engineering Guides
popularpost:
 - title: Getting to Statistical Signifiance
   link: /2023/09/11/statistical-significance-on-a-shoestring-budget.html
   description: No traffic, no problem! Updating your setup so you can keep experimenting.
 - title: Hiring, Training, and Culture
   link: /2023/09/27/how-to-build-a-growth-engineering-team-that-wins.html
   description: Starting, hiring, training, and setting culture for your Growth Engineering team. Co-authored with Elena Verna
 - title: Front-end Analytics Gotchas
   link: /2020/07/14/lies-damn-list-and-front-end-tracking.html
   description: "\"The slower your website, the better it converts\" and other lies your front-end analytics will tell you."
 - title: Lifecyle Marketing Tooling
   link: https://playbooks.hypergrowthpartners.com/p/picking-your-lifecycle-marketing
   description: How to select, implement and scaling marketing communication tooling, from 0 to IPO.

postlist:
 title: Latest Articles
 button: Explore all post
 limit: 8

paginationpage:
 next: _
 previous: More

footernavtitle: Menu
footernav1:
 nav: Home
 link: /
footernav2:
 nav: About
 link: /about
footernav3:
 nav: Growth
 link: /growth-eng
footernav4:
 nav: Contact
 link: mailto:alexey+contact-on-website@alexeymk.com

sharemodal:
 button: Share article
 title: Share this article
 description: In you liked this article share it with your friends. They will thank you later.
 email: email
 twitter: tweet
 facebook: facebook

social: #max 5 social
 facebook:
 twitter: https://twitter.com/alexeymk
 twitter_username: alexeymk
 rss: /feed.xml
 linked:
 youtube:
# instagram:


paginate: 10
paginate_path: '/:num/'

collections:
  services:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      permalink: /:year/:month/:title:output_ext.html
      permalink:
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
